### ISSUE TITLE
kilometri

### ISSUE THREAD

**Issue by FabioZTessitore** [luca998/while#2]
![es3_17](https://cloud.githubusercontent.com/assets/3002194/20533293/48c30aa0-b0dd-11e6-8a54-ba719cee8b78.png)

**Comment by FabioZTessitore** [comment]
va abbastanza bene, solo una nota:

ti trovi di fronte ad un problema del tipo: devo fare un ciclo, ma se non arriva l'input non so se posso proseguire oppure no. Lo hai risolto con la variabile `c`.
Un modo migliore è schematizzare così:
```
input
while (condizione)
    operazioni
    input
```

**Comment by luca998** [comment]
Quindi come condizione del while nel mio caso avrei dovuto mettere la variabile litri_utilizzati?

**Comment by FabioZTessitore** [comment]
si

**Comment by luca998** [comment]
Va bene ho capito

**Comment by luca998** [comment]
Ho un problema con i km al litro totali

**Comment by FabioZTessitore** [comment]
hai messo l'input all'interno del ciclo al posto sbagliato

poi dopo il ciclo perché hai tolto il controllo? se uno inserisce -1 già la prima volta?

**Comment by FabioZTessitore** [comment]
va bene
ricordati di usare double invece di float quando si tratta di variabili single (tanto comunque avviene una trasformazione prima della stampa)
l'ordine delle operazioni nel ciclo è un po' confuso (c'è una stampa che andrebbe dopo l'aggiornamento dei totali)
